### PR TITLE
Don't include sale if ended

### PR DESCRIPTION
**Pull request by tauqua**
I have no idea why GitHub is saying the entire file changed, the only changes are 122-126. This change reduces the number of requests processed

### CODE REVIEW

**Comment by Iron-Row** [comment]
It does this because line endings were accidently changed. To avoid this issue, use [git's core.autocrlf setting](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings). I also added a .gitattributes file to the repository.

I tried fixing the line endings myself but I think it's easier if you pull my most recent commit, fix your settings, and resubmit the PR.

BTW, you can see the different line endings by viewing or comparing [1](https://github.com/Iron-Row/claim_itch/raw/cbf71a641ea4f101474e3caf9cdb9f0c1e644d54/claim_itch.py) and [2](https://github.com/Iron-Row/claim_itch/raw/c57d2177ceb04a593587b62633f9064fc4a621d5/claim_itch.py) with a hex/binary tool. Also, you can see only the [important changes](https://github.com/Iron-Row/claim_itch/pull/5/files?w=1) by selecting "Hide whitespace changes".

**Comment by Iron-Row** [comment]
BTW, your commit and PR and made under different names. You might want to change your user.name and user.email in git's configuration if this isn't intentional :)

**Comment by tauqua** [comment]
Thanks for pointing that out. I messed up my repo enough trying to fix this that I just regenerated it, so I'll resubmit these PRs in a min.

**Comment by Iron-Row** [comment]
I have to apologize. It seems the cause was a mistake on my end when creating the repo.

I'll wait for your PR then try to sort out the line endings in a clean way (if needed). Then hopefully we can sync up without issues.

**Comment by Iron-Row** [comment]
GitHub might be showing a [commit](https://github.com/Iron-Row/claim_itch/commit/517904e77e9a75eeba678260b46d4213f792ece6) that references this PR.

Ignore it. I rolled it back once I saw your message.

**Pull request closed without merging**
